### ISSUE TITLE
Problema de limites de caracteres no console

### ISSUE THREAD

**Issue by RyanMouraBrocco** [RyanMouraBrocco/AtividadesC#6]
@bbissppoo Analise o código da branch "CriandoView"  no meu computador o console foi até o 39 sem a quebra de linha, acredito que era algo em relação ao compilador ou a versão do prompt de comando que você estava usando. Então vamos fazer o seguinte, em vez de usar para separar o "\t", usa alguns espaços apenas, e atentar para que, a partir da linha 10 e no 100 mude o espaçamento para que a matriz fique da maneira correta.

**Comment by gzaninotti** [comment]
Testei agora em outra maquina (minha pessoal) e obtive até o 26 sem quebra de linhas... Vou ver qual a solução que consigo para esse problema.

**Comment by RyanMouraBrocco** [comment]
@bbissppoo  acabei de subir uma atualização que resolve o problema da quebra de linha, porem, não cabe na tela todos os caracteres, coloquei o mínimo de espaço possível, na minha tela 21:9, consigo gerar o mundo 100X100 porem na tela 16:9 o máximo que cabe é 54X54
